---
- name: "Get etcd-ca content"
  slurp:
    src: "/etc/kubernetes/pki/etcd-ca.pem"
  register: cni_etcd_ca

- name: "Get etcd-client content"
  slurp:
    src: "/etc/kubernetes/pki/apiserver-etcd-client.pem"
  register: cni_etcd_cert

- name: "Get etcd-client content"
  slurp:
    src: "/etc/kubernetes/pki/apiserver-etcd-client.key"
  register: cni_etcd_key

- name: "Generate calico yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "calico-etcd-{{ calico.version }}.yaml.j2", dest: "/tmp/calico-etcd.yaml"}
  tags: calico

- name: "Deploy calico"
  shell: "kubectl apply -f /tmp/calico-etcd.yaml"
  tags: calico

