---
- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- name: "Install base application"
  apt: 
    name: ['ntpdate', 'git', 'vim', 'curl', 'wget', 'jq', 'psmisc', 'net-tools', 'telnet',  'lvm2', "apt-transport-https", "ca-certificates", "software-properties-common","ipvsadm", "ipset", "sysstat", "conntrack"] 
    update_cache: yes
    state: present
    cache_valid_time: 86400
  when: init_apt == "yes"

- name: update /etc/vim/vimrc
  blockinfile:
    dest: /etc/vim/vimrc
    marker: "\"{mark} ANSIBLE MANAGED BLOCK"
    block: |
      set nocompatible
      set history=50
      set fenc=utf-8
      set ruler
      set number
      set backspace=indent,eol,start
      set autoindent 
      set smartindent
      set cindent
      set tabstop=4
      set softtabstop=4
      set shiftwidth=4
      set expandtab
      set smarttab
      set showmatch
      set matchtime=5
      set hlsearch
      set incsearch
      set mouse=v
      set cursorline  
      filetype on
      syntax on


- name: "Remove swapfile from /etc/fstab"
  mount:
    name: "swap"
    fstype: sqap
    state: absent
  tags: swap

- name: "Set limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'memlock', value: 'unlimited' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'memlock', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags: limits

- name: "Set systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
  tags: limits

- name: "Enable module"
  template:
    src: "k8s_module.conf.j2"
    dest: "/etc/modules-load.d/k8s_module.conf"
  register: enable_module

- name: "Restart systemd-modules-load"
  service:
    name: "systemd-modules-load"
    state: restarted
  changed_when: false
  when: enable_module.changed == true


- name: "Modify sysctl"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'kernel.sysrq',value: '0' }
    - {name: 'vm.swappiness ',value: '0' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-ip6tables',value: '1' }
    - {name: 'vm.panic_on_oom',value: '0'}
    - {name: 'fs.inotify.max_user_watches', value: '89100'}
    - {name: 'net.netfilter.nf_conntrack_max',value: '2310720' }
  
    - {name: 'net.ipv4.tcp_keepalive_time',value: '600' }
    - {name: 'net.ipv4.tcp_keepalive_probes',value: '3' }
    - {name: 'net.ipv4.tcp_keepalive_intvl',value: '15' }
    #
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '36000' }
    - {name: 'net.ipv4.tcp_tw_reuse',value: '1' }
    - {name: 'net.ipv4.tcp_max_orphans',value: '327680' }
    - {name: 'net.ipv4.tcp_orphan_retries',value: '3' }
    #
    - {name: 'net.ipv4.tcp_syncookies ',value: '1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog',value: '16384' }
    # 
    - {name: 'net.ipv4.tcp_timestamps',value: '0' }
    - {name: 'net.core.somaxconn',value: '16384' }
    # 
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: '2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '30' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
    # 
    - {name: 'fs.file-max', value: "52706963"}
    - {name: 'fs.nr_open', value: "52706963"}
  tags: sysctl


## Start 动态加载模块 ##

# - name: "Enabled modlue"
#   modprobe:
#     name: "{{ item.line }}"
#     state: present
#   with_items:
#     - {line: 'ip_vs' }
#     - {line: 'ip_vs_sh' }
#     - {line: 'ip_vs_rr' }
#     - {line: 'ip_vs_wrr' }
#     - {line: 'ip_vs_wlc' }
#     - {line: 'ip_vs_lc' }
#     - {line: 'ip_vs_lblc' }
#     - {line: 'ip_vs_lblcr' }
#     - {line: 'ip_vs_dh' }
#     - {line: 'ip_vs_fo' }
#     - {line: 'ip_vs_nq' }
#     - {line: 'ip_vs_sed' }
#     - {line: 'ip_vs_ftp' }
#     - {line: 'bridge' }
#     - {line: 'overlay' }
#     - {line: 'br_netfilter' }
#     - {line: 'ip_tables' }
#     - {line: 'ip_set' }
#     - {line: 'ipt_set' }
#     - {line: 'ipt_rpfilter' }
#     - {line: 'ipt_REJECT' }
#     - {line: 'ipip' }
#   tags: mod


# - name: "Enabled conntrack modlue"
#   modprobe:
#     name: "nf_conntrack_ipv4"
#     state: present
#   when: ansible_kernel.split('-')[0] is version('4.19.0', '<')
#   tags: mod

# - name: "Enabled conntrack modlue"
#   modprobe:
#     name: "nf_conntrack"
#     state: present
#   when: ansible_kernel.split('-')[0] is version('4.19.0', '>=')
#   tags: mod

## 动态加载模块 End ##



## 自建环境中没有swap，本部分有待完善 ##
## Start 关闭swap ##
# - name: swap - disable swap
#   shell: "([ $(swapon -s | wc -l) -ge 1 ] && (swapoff -a && echo disable)) || echo already"
#   ignore_errors: yes
#   register: swapoff_result
#   changed_when: "swapoff_result.stdout.strip() == 'disable'"
#   notify:
#   - disable swap mount



# Todo    
# - name: disable swap mount
#   replace:
#     dest: /etc/fstab
#     regexp: '^([^#].*swap)'
#     replace: '#\1'

## 关闭swap End ##